blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('post/<slug:slug>', views.post, name="post"),
    path('category/<slug:slug>/', views.category, name="category"),
    path('search/', views.search, name="search"),
    path('create/', views.PostCreateView.as_view(), name="create"),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('profile/', views.profile, name='profile'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='blog_login'),
    path('logout/', views.custom_logout_view, name='blog_logout')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', include('helloweb.urls')),
                  path('', include('blog.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('shop/', include('shop.urls')),
                  path('cart/', include('cart.urls')),
                  path('orders/', include('orders.urls', namespace='orders')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from shop.models import Product


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product, quantity=1)
    return redirect('cart:cart_detail')

templates/cart/detail.html
{% extends 'blog/base.html' %}
{% load thumbnail %}
{% block main %}

<h2>Your cart</h2>
<table>
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
    </tr>
    {% for item in cart %}
    <tr>
        <td>{{item.product.title}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.price}}</td>
        <td>{{item.total_price}}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>Total:</td>
        <td>UAH {{ cart.get_total_price }}</td>
        <td><a href="{% url 'orders:order_create' %}">Confirm order</a></td>
    </tr>
</table>
{% endblock %}